import { ActionFunctionArgs } from '@remix-run/node'
import pkg from 'pg'
import { z } from 'zod'

const { DatabaseError } = pkg

import { userIs } from '~/lib/db/auth.server'
import { createSEO } from '~/lib/db/seo.server'
import { ConventionalActionResponse } from '~/lib/utils'

export const SeoUpdateSchmea = z.object({
    metaTitle: z.string(),
    metaDescription: z.string(),
    route: z.string(),
})

export const action = async ({ request }: ActionFunctionArgs) => {
    if (request.method !== 'POST') {
        return Response.json({
            err: 'Method not allowed',
        } satisfies ConventionalActionResponse)
    }

    await userIs(request, ['ADMIN'])

    const formData = await request.formData()
    const createSeoData = Object.fromEntries(formData)

    const zResult = SeoUpdateSchmea.safeParse(createSeoData)

    if (!zResult.success || !zResult.data) {
        const message = zResult.error.issues
            .map(issue => `${issue.message} ${issue.path[0]}`)
            .join(' & ')
        return Response.json({
            err: message,
        } satisfies ConventionalActionResponse)
    }

    try {
        const { seo } = await createSEO({
            metaTitle: zResult.data.metaTitle,
            metaDescription: zResult.data.metaDescription,
            route: zResult.data.route,
            autoGenerated: false,
        })
        return Response.json({
            msg: `SEO for ${seo.route || seo.metaTitle || 'unknown'} created`,
        } satisfies ConventionalActionResponse)
    } catch (error) {
        if (error instanceof DatabaseError) {
            return Response.json({
                err: error.detail,
            } satisfies ConventionalActionResponse)
        }

        console.error(error)
        return Response.json({
            err: 'Failed to create SEO',
        } satisfies ConventionalActionResponse)
    }
}
