import { type InferSelectModel } from 'drizzle-orm'
import { boolean, serial, varchar } from 'drizzle-orm/pg-core'

import { pgTable, timestampAttributes } from './helpers'

export type Seo = InferSelectModel<typeof seo>

export const seo = pgTable('seo', {
	id: serial('id').primaryKey(),
	metaTitle: varchar('meta_title', { length: 255 }),
	metaDescription: varchar('meta_description', { length: 255 }),
	keywords: varchar('keywords', { length: 255 }),
	ogImage: varchar('og_image', { length: 255 }),
	autoGenerated: boolean('auto_generated').notNull(),
	route: varchar('route', { length: 255 }).unique(),

	...timestampAttributes,
})
