import { relations, type InferSelectModel } from 'drizzle-orm'
import {
	boolean,
	integer,
	pgTable,
	serial,
	timestamp,
	varchar,
} from 'drizzle-orm/pg-core'

import { postsTable } from './posts'

export type Seo = InferSelectModel<typeof seosTable>

export const seosTable = pgTable('seos', {
	id: serial('id').primaryKey(),
	createdAt: timestamp('created_at').notNull().defaultNow(),
	updatedAt: timestamp('updated_at')
		.notNull()
		.defaultNow()
		.$onUpdate(() => new Date()),
	metaTitle: varchar('meta_title', { length: 255 }),
	metaDescription: varchar('meta_description', { length: 255 }),
	keywords: varchar('keywords', { length: 255 }),
	ogImage: varchar('og_image', { length: 255 }),
	autoGenerated: boolean('auto_generated').notNull(),
	route: varchar('route', { length: 255 }).unique(),

	postId: integer('post_id')
		.unique()
		.references(() => postsTable.id, { onDelete: 'cascade' }),
})

export const seosRelations = relations(seosTable, ({ one }) => ({
	post: one(postsTable, {
		fields: [seosTable.postId],
		references: [postsTable.id],
	}),
}))
