import 'dotenv/config'
import { drizzle } from 'drizzle-orm/node-postgres'
import * as schema from '../app/lib/db/schema'

const db = drizzle(process.env.DATABASE_URL, { schema })

function isEmailValid(email) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

async function checkAndCreateAdmin() {
    try {
        // Check if admin exists
        const admin = await db.query.usersTable.findFirst({
            where: (t, { eq }) => eq(t.role, 'ADMIN'),
        })

        if (!admin) {
            console.log('Check Admin: Admin user does not exist. Creating...')

            // Check if email exists
            const email = process.env.SUPER_EMAIL
            if (!email) {
                console.error('Check Admin: Fail to create first admin user.')
                console.warn(
                    'You should provide your email via "--".\nRun: "npm run dev --email=your@ema.il" instead.'
                )
                return process.exit(1)
            }

            // Check if email is valid
            if (!isEmailValid(email)) {
                console.error('Check Admin: Invalid email format.')
                return process.exit(1)
            }

            // Create admin user and papa SEO
            const [newAdmin] = await db.transaction(async tx => {
                await tx.insert(schema.seosTable).values({
                    route: '/',
                    metaTitle: 'Papa',
                    metaDescription:
                        'Papa - A simple and thorough platform for modern web app.',
                    autoGenerated: true,
                })

                return await tx
                    .insert(schema.usersTable)
                    .values({
                        email,
                        role: 'ADMIN',
                        status: 'ACTIVE',
                    })
                    .returning()
            })

            console.log('\nCheckAdmin: Admin user created:', newAdmin)
            console.warn(
                `\n* * * \nAdmin user created! Sign in with ${newAdmin.email}.\n* * *\n`
            )
        } else {
            console.log('Check Admin: Admin user already exists.\n')
        }
    } catch (error) {
        console.error('Check Admin: Error checking/creating admin user:', error)
    } finally {
        process.exit(0)
    }
}

checkAndCreateAdmin()
