import 'dotenv/config'

import * as readline from 'readline'

import { eq, sql } from 'drizzle-orm'
import { drizzle } from 'drizzle-orm/node-postgres'
import { pgSchema } from 'drizzle-orm/pg-core'

import { auth } from '~/lib/auth/auth.server'
import type { TransactionType } from '~/lib/db/db.server'
import { isValidEmail } from '~/lib/utils'

import * as schema from '../app/lib/db/schema'

const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout,
})

const askEmail = (): Promise<string> => {
	return new Promise(resolve => {
		rl.question(
			'\n❓ 請輸入管理員電子郵件地址 (Please enter Admin Email) (按下 ^+C 以關閉) (Press ^+C to exit): ',
			email => {
				if (!isValidEmail(email)) {
					console.error(
						'❌ 無效的電子郵件格式，請重新輸入。(Invalid email, try again.)',
					)
					return resolve(askEmail())
				}
				resolve(email)
			},
		)
	})
}

const askName = (): Promise<string> => {
	return new Promise(resolve => {
		rl.question(
			'\n❓ 設定您的名字 (Please enter your name) (按下 ^+C 以關閉) (Press ^+C to exit): ',
			name => resolve(name),
		)
	})
}

async function checkAndCreateAdmin() {
	const db = drizzle(process.env.DATABASE_URL!, { schema })

	await db.transaction(async tx => {
		await insertDefaultData(tx, 'psRr2HBzP8Fv7Nxyvr45KY4mpcLu1sCY')
		tx.execute(sql`create schema if not exists ${pgSchema('default')}`)
	})

	try {
		// Check if admin exists
		const admin = await db.query.user.findMany({
			where: (t, { eq }) => eq(t.role, 'admin'),
			orderBy: (t, { asc }) => asc(t.createdAt),
		})

		if (admin.length === 0) {
			const email = await askEmail()
			const name = await askName()

			// Create admin
			console.log(
				'\n🔄 管理員不存在，正在建立... (Admin does not exist. Creating...)',
			)
			const { user } = await auth.api.createUser({
				body: {
					email: email,
					password: '',
					name: name,
					role: 'admin',
				},
			})
			await db
				.update(schema.user)
				.set({
					emailVerified: true,
				})
				.where(eq(schema.user.id, user.id))

			console.log(
				`✅ 管理員已建立！請使用 ${'user.email'} 登入。 (Admin created! Sign in with ${'user.email'})`,
			)

			console.log('🔄 正在建立預設資料 (Inserting default data)...')
			await db.transaction(async tx => {
				await insertDefaultData(tx, user.id)
				tx.execute(sql`create schema if not exists ${pgSchema('default')}`)
			})
			console.log('✅ 預設資料已建立 (Default data created)')
		} else {
			console.log(`⚠️ 管理員已存在。Admin already exists.`)
		}
	} catch (error) {
		console.error(
			'❌ 檢查/建立管理員使用者時發生錯誤 (Error checking/creating admin):',
			error,
		)
		process.exit(1)
	} finally {
		process.exit(0)
	}
}

const insertDefaultData = async (tx: TransactionType, adminId: string) => {
	await tx.insert(schema.seosTable).values(defaultSEOs)

	const [postCreated] = await tx
		.insert(schema.postsTable)
		.values({
			authorId: adminId,
			title: defaultPost.title,
			content: defaultPost.content,
			slug: defaultPost.slug,
			excerpt: defaultPost.excerpt,
			status: defaultPost.status,
			featuredImage: defaultPost.featuredImage,
		})
		.returning()
	console.log('\n✅ 預設文章已建立 (Default post created):', postCreated.title)

	await tx.insert(schema.seosTable).values({
		metaTitle: defaultPost.title,
		metaDescription: defaultPost.excerpt,
		autoGenerated: true,
		postId: postCreated.id,
		route: '/blog/' + postCreated.slug,
	})
	console.log(
		'\n✅ 預設文章 SEO 已建立 (Default post SEO created):',
		defaultPost.title,
	)

	const tags = await tx.insert(schema.tagsTable).values(defaultTags).returning()
	console.log(
		'\n✅ 預設標籤已建立 (Default tags created):',
		defaultTags.map(tag => ({
			name: tag.name,
		})),
	)

	const categories = await tx
		.insert(schema.categoriesTable)
		.values(defaultCategories)
		.returning()
	console.log(
		'\n✅ 預設分類已建立 (Default categories created):',
		defaultCategories.map(category => ({
			name: category.name,
		})),
	)

	await tx.insert(schema.postsToTags).values(
		tags.map(tag => ({
			postId: postCreated.id,
			tagId: tag.id,
		})),
	)

	await tx.insert(schema.postsToCategories).values(
		categories.map(category => ({
			postId: postCreated.id,
			categoryId: category.id,
		})),
	)
	console.log(
		'\n✅ 預設文章與標籤、分類關聯已建立 (Default post to tags and categories created)',
	)
}

const defaultSEOs = [
	{
		autoGenerated: true,
		route: '/',
		metaTitle: 'Papa - First and only online application for SMEs ⛰️',
		metaDescription: `Papa is a simple and thorough platform for modern SMEs.
            With one Papa, you can manage your internal workflow and external presence all together.
        `.replace(/\s+/g, ' '),
	},
	{
		autoGenerated: true,
		route: '/blog',
		metaTitle: 'Blog - Where you see my sounds 🎵',
		metaDescription: 'This is where I share my thoughts and insights.',
	},
	{
		autoGenerated: true,
		route: '/admin',
		metaTitle: 'Papa Admin Panel',
	},
]
const defaultPost = {
	slug: 'what-is-papa',
	title: 'What is Papa',
	content: JSON.stringify({
		type: 'doc',
		content: [
			{
				type: 'heading',
				attrs: { textAlign: null, level: 2 },
				content: [
					{
						type: 'text',
						text: '🥔 Papa — The AI-Native App Framework for SMEs',
					},
				],
			},
			{
				type: 'blockquote',
				content: [
					{
						type: 'paragraph',
						attrs: { textAlign: null },
						content: [
							{
								type: 'text',
								marks: [{ type: 'bold' }],
								text: 'Papa is an AI-native open-source application designed to help SMEs manage both internal workflows and external presence — all in one place.',
							},
						],
					},
				],
			},
			{
				type: 'paragraph',
				attrs: { textAlign: null },
				content: [
					{
						type: 'text',
						text: "What's better? You own the code. Forever. 🚀",
					},
				],
			},
			{ type: 'horizontalRule' },
			{
				type: 'heading',
				attrs: { textAlign: null, level: 3 },
				content: [{ type: 'text', text: "✨ Features you'll love" }],
			},
			{
				type: 'bulletList',
				content: [
					{
						type: 'listItem',
						content: [
							{
								type: 'paragraph',
								attrs: { textAlign: null },
								content: [{ type: 'text', text: '✅ Fully responsive layout' }],
							},
						],
					},
					{
						type: 'listItem',
						content: [
							{
								type: 'paragraph',
								attrs: { textAlign: null },
								content: [{ type: 'text', text: '🌙 Dark mode support' }],
							},
						],
					},
					{
						type: 'listItem',
						content: [
							{
								type: 'paragraph',
								attrs: { textAlign: null },
								content: [
									{
										type: 'text',
										text: '📝 Beautiful, intuitive rich text editing powered by ',
									},
									{ type: 'text', marks: [{ type: 'bold' }], text: 'Tiptap' },
								],
							},
						],
					},
					{
						type: 'listItem',
						content: [
							{
								type: 'paragraph',
								attrs: { textAlign: null },
								content: [
									{
										type: 'text',
										text: '🧠 Smart structure with Markdown + syntax highlighting',
									},
								],
							},
						],
					},
					{
						type: 'listItem',
						content: [
							{
								type: 'paragraph',
								attrs: { textAlign: null },
								content: [
									{
										type: 'text',
										text: '🎨 Supports all common text styles — ',
									},
									{ type: 'text', marks: [{ type: 'bold' }], text: 'bold' },
									{ type: 'text', text: ', ' },
									{ type: 'text', marks: [{ type: 'italic' }], text: 'italic' },
									{ type: 'text', text: ', ' },
									{
										type: 'text',
										marks: [{ type: 'code' }],
										text: 'inline code',
									},
									{ type: 'text', text: ', ' },
									{
										type: 'text',
										marks: [{ type: 'code' }],
										text: 'code blocks',
									},
									{ type: 'text', text: ', super⁺sub, and more!' },
								],
							},
						],
					},
				],
			},
			{
				type: 'codeBlock',
				attrs: { language: null },
				content: [
					{
						type: 'text',
						text: '// TypeScript Example\nconst Papa = (papa: string) => {\n  alert(`${Papa} is free and open source under MIT license!`)\n}',
					},
				],
			},
			{
				type: 'codeBlock',
				attrs: { language: null },
				content: [
					{
						type: 'text',
						text: '// Golang Hello World\nfunc main() {\n\tfmt.Println("Hello, 世界")\n\tfmt.Println("Hello, せかい")\n\tfmt.Println("Hola, mundo")\n}',
					},
				],
			},
			{
				type: 'blockquote',
				content: [
					{
						type: 'paragraph',
						attrs: { textAlign: null },
						content: [
							{
								type: 'text',
								text: '⚠️ H1 is reserved for titles — please use H2–H4 in your content.',
							},
						],
					},
				],
			},
			{ type: 'horizontalRule' },
			{
				type: 'heading',
				attrs: { textAlign: null, level: 3 },
				content: [{ type: 'text', text: '🚀 Get Started Now' }],
			},
			{
				type: 'heading',
				attrs: { textAlign: null, level: 4 },
				content: [{ type: 'text', text: '1. Clone the repo' }],
			},
			{
				type: 'codeBlock',
				attrs: { language: null },
				content: [
					{
						type: 'text',
						text: 'git clone https://github.com/gjc14/papa.git ',
					},
				],
			},
			{
				type: 'heading',
				attrs: { textAlign: null, level: 4 },
				content: [{ type: 'text', text: '2. Set up your environment' }],
			},
			{
				type: 'codeBlock',
				attrs: { language: null },
				content: [{ type: 'text', text: 'mv .env.sample .env ' }],
			},
			{
				type: 'heading',
				attrs: { textAlign: null, level: 4 },
				content: [{ type: 'text', text: '3. Initialize the app' }],
			},
			{
				type: 'codeBlock',
				attrs: { language: null },
				content: [{ type: 'text', text: 'npm run init ' }],
			},
			{
				type: 'paragraph',
				attrs: { textAlign: null },
				content: [
					{ type: 'text', text: 'Then open your browser and go to ' },
					{ type: 'text', marks: [{ type: 'code' }], text: 'localhost:5173' },
					{ type: 'text', text: ' to see ' },
					{ type: 'text', marks: [{ type: 'bold' }], text: 'your Papa' },
					{ type: 'text', text: ' in action!' },
				],
			},
			{ type: 'horizontalRule' },
			{
				type: 'heading',
				attrs: { textAlign: null, level: 3 },
				content: [{ type: 'text', text: '💬 Why Papa?' }],
			},
			{
				type: 'blockquote',
				content: [
					{
						type: 'paragraph',
						attrs: { textAlign: null },
						content: [
							{
								type: 'text',
								text: 'Papa helps developers and teams build internal tools, portals, and public sites — fast.',
							},
							{ type: 'hardBreak' },
							{
								type: 'text',
								text: 'You get the flexibility of code, the speed of modern frameworks, and ',
							},
							{
								type: 'text',
								marks: [{ type: 'bold' }],
								text: 'no vendor lock-in',
							},
							{ type: 'text', text: '.' },
						],
					},
				],
			},
			{
				type: 'paragraph',
				attrs: { textAlign: null },
				content: [
					{ type: 'text', text: "🧑‍💻 It's yours. It's fast. It's open source." },
				],
			},
		],
	}),
	excerpt:
		"Papa is an AI Native for SMEs to manage both internal workflow and external image. What's better? It's open souce!",
	featuredImage:
		'https://images.unsplash.com/photo-1552993873-0dd1110e025f?q=80&w=2765&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
	status: 'PUBLISHED',
}
const defaultTags = [
	{
		name: 'Papa',
		slug: 'papa',
	},
	{
		name: 'Open Source',
		slug: 'open-source',
	},
]
const defaultCategories = [
	{
		name: 'SMEs',
		slug: 'smes',
	},
	{
		name: 'ERP',
		slug: 'erp',
	},
	{
		name: 'SEO',
		slug: 'seo',
	},
	{
		name: 'CWM',
		slug: 'cwm',
	},
]

await checkAndCreateAdmin()
